DRS/ViewModels/Supplier_BrandViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DRS.Entities;

namespace DRS.ViewModels
{
    public class Supplier_BrandViewModel
    {
    }
    public class Supplier_BrandListingViewModel
    {
        public List<DisplayModelForRelation> BrandListing { get; set; }
           
        //public string BrandLogo { get; set; }
        //public string BrandDescription { get; set; }
        //public string SupplierDescription { get; set; }
        //public string Default { get; set; }
        //public string Note { get; set; }

    }
    public class DisplayModelForRelation
    {
        public int ID { get; set; }
        public string BrandLogo { get; set; }
        public string BrandDescription { get; set; }
        public string SupplierDescription { get; set; }
        public string Default { get; set; }
        public string Note { get; set; }
    }

    public class Supplier_BrandActionViewModel
    {
        public List<Branch> Branches { get; set; }
        public List<Customer> Customer { get; set; }
        public List<Supplier> Supplier { get; set; }
        public List<Brand> Brands { get; set; }

        public int ID { get; set; }
        public int IDSupplier { get; set; }
        public int IDBrand { get; set; }
        public string Default { get; set; }
        public string Note { get; set; }

    }
}

DRS/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DRS.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult UploadPhotos()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];

                var fileName = DateTime.Now.ToString("dd-MM-yyyy") + file.FileName;

                var path = Path.Combine(Server.MapPath("~/Photos/"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, DocURL = string.Format("/Photos/{0}", fileName) };
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
                throw;
            }
            return result;
        }

        public FileResult DownloadFile(string path)
        {
            if (System.IO.File.Exists(Server.MapPath(path)))
            {
                // Determine the content type (MIME type) of the file
                string contentType = MimeMapping.GetMimeMapping(Server.MapPath(path));

                // Read the file data into a byte array
                byte[] fileBytes = System.IO.File.ReadAllBytes(Server.MapPath(path));

                // Create a FileContentResult to send the file to the client
                return File(fileBytes, contentType, Path.GetFileName(Server.MapPath(path)));
            }
            else
            {
                // Return a not found response if the file doesn't exist
                return null;
            }
        }

        public JsonResult ArticleUploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/template/images/"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/Content/template/images/{0}", fileName) };
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
                throw;
            }
            return result;
        }

    }
}

DRS/Controllers/Supplier_BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DRS.Entities;
using DRS.Services;
using DRS.ViewModels;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace DRS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class Supplier_BrandController : Controller
    {
        // GET: Supplier_Brand
        public ActionResult Index(string SearchTerm = "")
        {
            Session["ACTIVER"] = "Supplier/Brand";

            Supplier_BrandListingViewModel model = new Supplier_BrandListingViewModel();
            var datalist = new List<DisplayModelForRelation>();
            
            var Supplier_Brands = Supplier_BrandServices.Instance.GetSupplier_Brands();
            foreach (var item in Supplier_Brands)
            {
                DisplayModelForRelation data = new DisplayModelForRelation();
                data.ID = item.ID;
                var branddata = BrandServices.Instance.GetBrandById(item.IDBrand);
                data.BrandLogo = branddata.Logo;
                data.BrandDescription = branddata.Description;

                var supplierdata = SupplierServices.Instance.GetSupplierById(item.IDSupplier);
                data.SupplierDescription = supplierdata.Description;
                data.Default = item.Default;
                data.Note = item.Note;
                datalist.Add(data);
            }
            model.BrandListing = datalist;
            return View("Index", model);
        }
        [HttpGet]
        public ActionResult Import()
        {
            Session["ACTIVER"] = "Supplier/Brand Import";

            return View();
        }
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile)
        {
            if (excelfile == null || excelfile.ContentLength == 0)
            {
                ViewBag.Error = "Please Select Excel File";
                return View();
            }
            else
            {
                var items = new List<Supplier_Brand>();
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial; // or LicenseContext.Commercial

                if (excelfile != null && excelfile.ContentLength > 0)
                {
                    using (var package = new ExcelPackage(excelfile.InputStream))
                    {
                        var worksheet = package.Workbook.Worksheets[0];
                        var rowCount = worksheet.Dimension.Rows;


                        for (int row = 2; row <= rowCount; row++) // Assuming the first row is header
                        {

                            var Supplier_Brand = new Supplier_Brand();

                            if (worksheet.Cells[row, 1].Value == null || worksheet.Cells[row, 2].Value == null)
                            {
                                continue;
                            }

                            if (worksheet.Cells[row, 1].Value != null)
                            {
                                var brand = BrandServices.Instance.GetBrand(worksheet.Cells[row, 1].Value.ToString()).FirstOrDefault();
                                if (brand != null)
                                {
                                    Supplier_Brand.IDBrand = brand.ID;
                                }
                                else
                                {
                                    var Brand = new Brand();
                                    Brand.Description = worksheet.Cells[row, 1].Value.ToString();
                                    BrandServices.Instance.CreateBrand(Brand);
                                    var NewBrand = BrandServices.Instance.GetLastEntryId();
                                    Supplier_Brand.IDBrand = NewBrand;
                                }
                            }
                            if (worksheet.Cells[row, 2].Value != null)
                            {
                                var Supplier = SupplierServices.Instance.GetSupplier(worksheet.Cells[row, 2].Value.ToString()).FirstOrDefault(); ;
                                if (Supplier != null)
                                {
                                    Supplier_Brand.IDSupplier = Supplier.ID;
                                }
                                else
                                {
                                    var supplier = new Supplier();
                                    supplier.Description = worksheet.Cells[row, 2].Value.ToString();
                                    SupplierServices.Instance.CreateSupplier(supplier);
                                    var NewSupplier = SupplierServices.Instance.GetLastEntryId();
                                    Supplier_Brand.IDSupplier = NewSupplier;
                                }

                            }
                           
                            if (worksheet.Cells[row, 3].Value != null)
                            {
                                Supplier_Brand.Note = worksheet.Cells[row, 3].Value.ToString();
                            }
                            else
                            {
                                Supplier_Brand.Note = "Not Specified";
                            }

                           

                            items.Add(Supplier_Brand);
                            Supplier_BrandServices.Instance.CreateSupplier_Brand(Supplier_Brand);
                        }

                    }
                    ViewBag.Products = items;
                    return View();

                }



                else
                {
                    ViewBag.Error = "Incorrect File";

                    return View();
                }
            }

            //var Prcoess = Process.GetProcessesByName("EXCEL.EXE").FirstOrDefault();
            //Prcoess.Kill();

        }
        public ActionResult ExportToExcel()
        {

            var relation = Supplier_BrandServices.Instance.GetSupplier_Brands();


            System.Data.DataTable tableData = new System.Data.DataTable();
            tableData.Columns.Add("ID", typeof(int)); // Replace "Column1" with the actual column name
            tableData.Columns.Add("Marca", typeof(string));
            tableData.Columns.Add("Fornitore", typeof(string)); // Replace "Column1" with the actual column name                                                            // Replace "Column2" with the actual column name
            tableData.Columns.Add("Default", typeof(string)); // Replace "Column2" with the actual column name// Replace "Column2" with the actual column name
            tableData.Columns.Add("Note", typeof(string)); // Replace "Column2" with the actual column name

            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

            foreach (var item in relation)
            {
                DataRow row = tableData.NewRow();
                row["ID"] = item.ID;

                var brand = BrandServices.Instance.GetBrandById(item.IDBrand);
                row["Marca"] = brand.Description;

                var supplier = SupplierServices.Instance.GetSupplierById(item.IDSupplier);
                row["Fornitore"] = supplier.Description;

                if(item.Default == "on")
                {
                    row["Default"] = "Yes";

                }
                else
                {
                    row["Default"] = "No";

                }

                row["Note"] = item.Note;


                tableData.Rows.Add(row);
            }





            // Create the Excel package
            using (ExcelPackage package = new ExcelPackage())
            {
                // Create a new worksheet
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Products");

                // Set the column names
                for (int i = 0; i < tableData.Columns.Count; i++)
                {
                    worksheet.Cells[1, i + 1].Value = tableData.Columns[i].ColumnName;
                }

                // Set the row data
                for (int row = 0; row < tableData.Rows.Count; row++)
                {
                    for (int col = 0; col < tableData.Columns.Count; col++)
                    {
                        worksheet.Cells[row + 2, col + 1].Value = tableData.Rows[row][col];
                    }
                }

                // Auto-fit columns for better readability
                worksheet.Cells.AutoFitColumns();

                // Convert the Excel package to a byte array
                byte[] excelBytes = package.GetAsByteArray();

                // Return the Excel file as a downloadable file
                return File(excelBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Supplier/Brand.xlsx");
            }
        }
        [HttpGet]
        public ActionResult Action(int ID = 0)
        {
            if (ID != 0)
            {
                Session["ACTIVER"] = "Supplier/Brand Edit";
            }
            else
            {
                Session["ACTIVER"] = "Add Supplier/Brand";

            }
            Supplier_BrandActionViewModel model = new Supplier_BrandActionViewModel();
            if (ID != 0)
            {
                var Supplier_Brand = Supplier_BrandServices.Instance.GetSupplier_BrandById(ID);
                model.ID = Supplier_Brand.ID;
                model.IDBrand = Supplier_Brand.IDBrand;
                model.IDSupplier = Supplier_Brand.IDSupplier;
                model.Default = Supplier_Brand.Default;
                model.Note = Supplier_Brand.Note;
            }
            model.Brands = BrandServices.Instance.GetBrands();
            model.Supplier = SupplierServices.Instance.GetSuppliers();
            return View("Action", model);
        }


        [HttpPost]
        public ActionResult Action(Supplier_BrandActionViewModel model)

DRS/Views/Supplier_Brand/Action.cshtml
@model DRS.ViewModels.Supplier_BrandActionViewModel
@{
    ViewBag.Title = "Action";
}
<style>
    .form-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
    }

    .container-bottom {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .back {
        margin-right: 10px;
    }

    .col-md-8 {
        display: flex;
        justify-content: space-between;
    }

    input {
        width: 400px;
    }

    .setter {
        position: relative;
        left: -254px;
    }
</style>
@if (Model != null)
{
    <div class="card">
        <div class="card-body">
           
                <form id="actionForm">
                    <div class="form-container">
                        <input value="@Model.ID" type="hidden" class="form-control" name="ID" id="ID" />
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="IDBrand">Brand:</label>
                                    <select class="form-control" name="IDBrand" id="IDBrand">
                                        @foreach (var item in Model.Brands)
                                        {
                                            <option value="@item.ID" @(item.ID == Model.IDBrand ? "selected" : "")>@item.Description</option>
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="IDSupplier">Supplier:</label>
                                    <select class="form-control" name="IDSupplier" id="IDSupplier">
                                        @foreach (var item in Model.Supplier)
                                        {
                                            <option value="@item.ID" @(item.ID == Model.IDSupplier ? "selected" : "")>@item.Description</option>
                                        }
                                    </select>
                                </div>
                            </div>

                            @if (Model.ID != 0)
                            {
                                if (Model.Default == "on")
                                {
                                    <div class="form-group col-md-1">
                                        <label for="Default">Default&nbsp;</label>
                                        <input type="checkbox" class="form-control" name="Default" id="Default" checked="checked" style="width: 10px; height: 10px; padding: 0;"/>
                                    </div>
                                }
                                else
                                {
                                    <div class="form-group col-md-1">
                                        <label for="Default">Default&nbsp;</label>
                                        <input type="checkbox" class="form-control" name="Default" id="Default" style="width: 10px; height: 10px; padding: 0;"/>
                                    </div>
                                }

                            }
                            else
                            {
                                <div class="form-group col-md-3">
                                    <label for="Default">Default&nbsp;</label>
                                    <input type="checkbox" class="form-control" name="Default" id="Default" />
                                </div>

                            }

                            <div class="form-group col-md-7">
                                <label for="Note">Note &nbsp;</label>
                                <input value="@Model.Note" type="text" class="form-control" name="Note" id="Note" />
                            </div>

                        </div>
                       
                    </div>

                </form>



                <div class="errorDiv">

                </div>
           
            <div style="background-color:white;" class="card-footer container-bottom">
                <a href="@Url.Action("Index","Supplier_Brand")" class="btn btn-danger back btn-rounded"><i class="fas fa-times mr-1"></i> Cancel</a>
                @if (Model.ID != 0)
                {
                    <button id="actionButton" type="button" class="btn btn-success btn-rounded"><i class="fas fa-save mr-1"></i> Update</button>
                }
                else
                {
                    <button id="actionButton" type="button" class="btn btn-success btn-rounded"><i class="fas fa-save mr-1"></i> Save</button>
                }

            </div>

        </div>
    </div>
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>

    $("#actionButton").click(function () {
        $("#actionButton").attr("disabled", "disabled");
        showLoadingSpinner();

		$.ajax({
			url: '@Url.Action("Action", "Supplier_Brand")',
			type: "post",
			data: $("#actionForm").serialize()
		})
            .done(function (response) {
			if(response.success)
			{
				window.location.href = "@Url.Action("Index", "Supplier_Brand")";
			}
			else {
				$(".errorDiv").html(response.Message);
			}
		});
    });

   $("#PhotoUpload").change(function () {
        var element = this;
        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadPhotos", "Shared")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {

                console.log(response);
                if (response.Success) {
                    $("#_Photo").val(response.DocURL);
                    $("#PhotoImg").attr("src", response.DocURL);

                }

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
    });
</script>

DRS/Views/Supplier_Brand/Import.cshtml
@{
    ViewBag.Title = "Import";
}
<script src="https://www.appelsiini.net/download/jquery.jeditable.js"></script>
<style>
    .top-page {
        display: flex;
        justify-content: space-between;
    }

    .mover {
        margin-top: -30px;
    }
</style>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Import", "Supplier_Brand", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Raw(ViewBag.Error)
            <br />
            <div class="top-page">
                <div>
                    <span>
                        Excel File
                    </span>
                </div>
                <div>
                    <a class="btn btn-success mover" href="@Url.Action("DownloadFile", "Shared", new { path = "~/Content/DemoFiles/SupplierBrandDemoImport.xlsx" })">
                        <i class="fa fa-download" aria-hidden="true"></i>Demo File
                    </a>
                </div>
            </div>

            <input class="form-control" type="file" name="excelfile" />
            <br />
            <input class="btn btn-block btn-outline-primary" type="submit" value="Import" />
            <br />
        }
        <a class="btn btn-block btn-outline-success" href="@Url.Action("Index","Supplier_Brand")">Back to Supplier/Brands</a>


        @if (ViewBag.Products != null)
        {
            <table class="table table-responsive" cellpadding="2" cellspacing="2" bSupplier_Brand="1">
                <tr>
                    
                    <th>
                        Status
                    </th>

                </tr>
                
                @foreach (var item in ViewBag.Products)
                {
                    <tr>
                        <td>IMPORTED</td>
                    </tr>
                }
            </table>
        }


    </div>
</div>

DRS/Views/Supplier_Brand/Index.cshtml
@model DRS.ViewModels.Supplier_BrandListingViewModel

@{
}
<style>
    .blue {
        background: #3947e7;
        color: white;
    }
    .addbtn {
        border-radius: 50%;
        padding: 10px;
        background: black;
        color: white;
        border: 1px solid black;
    }

    .container-top {
        display: flex;
    }

    .fa-download {
        color: blue; /* Set the default color to blue */
        transition: color 0.3s; /* Add a smooth color transition */
    }

        .fa-download:hover {
            color: black; /* Change the color to black on hover */
        }

    .dataTables_filter {
        float: right;
    }
    .top-portion {
        width: 100%;
        display: flex;
        justify-content: space-between;
    }

    #searchdropdown {
        margin-left: 30px;
    }
</style>

<div class="container">
    <div class="card">
        <div class="card-body  container-top">
         
            <div class="top-portion">
                <div class="input-group-prepend flexer">
                    <span class="input-group-text"><i class="fa fa-search"></i></span>
                    <input id="searchbar" class="form-control" placeholder="Search">
                    <select id="searchdropdown">
                        <option value="Fornitore">Fornitore</option>
                        <option value="Marca">Marca</option>
                    </select>
                </div>
                <form>

                    <div class="input-group">
                        <a href="@Url.Action("Import", "Supplier_Brand")" class=" btn btn-rounded blue"><i class="fas fa-upload"></i>&nbsp; Import</a>

                        <a href="@Url.Action("ExportToExcel", "Supplier_Brand")" class=" btn btn-rounded blue"><i class="fas fa-upload"></i>&nbsp; Export</a>

                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <a href="@Url.Action("Action", "Supplier_Brand")" class=" btn btn-rounded blue"><i class="fas fa-plus"></i>&nbsp; Aggiungi</a>

                    </div>
                </form>
            </div>
        </div>
    </div>
    @if (Model.BrandListing != null)
    {
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    

                        <div class="card col-md-12">

                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Azioni</th>
                                            <th>Logo</th>
                                            <th>Marca</th>
                                            <th>Fornitore</th>
                                            <th>Default</th>
                                            <th>Note</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.BrandListing)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="dropdown">
                                                        <button class="btn btn-sm btn-rounded btn-secondary btn-icon-text dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="fa fa-list" aria-hidden="true"></i>

                                                        </button>
                                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                            <a class="dropdown-item" href="@Url.Action("Action", "Supplier_Brand", new { ID = item.ID })">
                                                                <i class="mdi mdi-pencil"></i> Modifica
                                                            </a>
                                                            @*<button data-href="@Url.Action("Delete", "Supplier_Brand", new { ID = item.ID })" class="dropdown-item data-btn btn btn-danger btn-icon-text" data-toggle="modal" data-target="#actionModal"><i class="mdi mdi-delete"></i>DELETE</button>*@

                                                            <a class="data-btn dropdown-item" data-href="@Url.Action("Delete", "Supplier_Brand", new { ID = item.ID })" data-toggle="modal" data-target="#actionModal">
                                                                <i class="mdi mdi-delete"></i> DELETE
                                                            </a>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    @if (item.BrandLogo != null)
                                                    {
                                                        <img style="height:50px; width:50px;" src="@item.BrandLogo" />

                                                    }
                                                    else
                                                    {
                                                        <img style="height:50px; width:50px;" src="~/Content/DRS Content/Images/download.png" />

                                                    }
                                                </td>
                                                <td>@item.BrandDescription</td>
                                                <td>@item.SupplierDescription</td>
                                                <td>
                                                    @if (item.Default == "on")
                                                    {
                                                        <input disabled type="checkbox" checked="checked" />
                                                    }
                                                    else
                                                    {
                                                        <input disabled type="checkbox" />
                                                    }
                                                </td>
                                                <td>@item.Note</td>
                                                @*<td>@item._File</td>*@
                                                @*<td>
            <a class="btn" href="@Url.Action("DownloadFile", "Shared", new { path = item._File })">
                <i class="fa fa-download" aria-hidden="true"></i>
            </a>
        </td>*@
                                            </tr>
                                        }
                                    </tbody>

                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                   
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
    }
    else
    {

        <div class="alert alert-warning col-md-12" role="alert">
            Sorry! No records exist.
        </div>
    }
</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

<script>
    $(document).ready(function () {
        var tableBody = $('#example1 tbody');
        var originalRows = tableBody.find('tr').clone();
        var dropdownValue = $('#searchdropdown').val();

        $('#searchbar').on('input', function () {
            var inputValue = $(this).val().trim().toLowerCase();
            var dropdownValue = $('#searchdropdown').val();

            tableBody.empty();

            originalRows.each(function () {
                var row = $(this);
                if (dropdownValue === "Fornitore") {
                    var fornitoreCell = row.find('td:eq(3)').text().toLowerCase(); // Index 3 corresponds to the "Fornitore" column

                } else {
                    var fornitoreCell = row.find('td:eq(2)').text().toLowerCase(); // Index 3 corresponds to the "Fornitore" column

                }

                if (fornitoreCell.includes(inputValue)) {
                    tableBody.append(row.clone());
                }
            });
        });
    })
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#actionModal .modal-dialog").html(response);
            });
    });
</script>